version: "3"
services:
  x-redash-service: &redash-service
    image: $IMAGE_REDASH
    depends_on:
      - postgres
      - redis
    env_file: dot-env
    restart: always
  server:
    <<: *redash-service
    command: server
    ports:
      - "5000:5000"
    environment:
      REDASH_WEB_WORKERS: 4
  scheduler:
    <<: *redash-service
    command: scheduler
    environment:
      QUEUES: "celery"
      WORKERS_COUNT: 1
  scheduled_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "scheduled_queries,schemas"
      WORKERS_COUNT: 1
  adhoc_worker:
    <<: *redash-service
    command: worker
    environment:
      QUEUES: "queries"
      WORKERS_COUNT: 2
  redis:
    image: $IMAGE_REDIS
    restart: always
  postgres:
    image: $IMAGE_POSTGRES
    env_file: dot-env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
  nginx:
    image: $IMAGE_NGINX
    ports:
      - "80:80"
    depends_on:
      - server
    links:
      - server:redash
    restart: always
volumes:
  postgres-data:
